#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail; shopt -s nullglob
root=${0%/*}
file=$(basename "${BASH_SOURCE[0]}")
cd $root

. ../lib/cli-utils
. ../lib/thinder-environment.sh

set_thinder_description "Manage the Thinder environment storage"

function usage {
	local cmdlen=${#file}
	echo "Usage: ${file/\-/ } [args...]"
	echo
	echo $THINDER_DESCRIPTION
	echo
	echo "Options:"
	echo "  -h, --help                 Print this usage information"
	echo
	echo "Commands:"
	echo "    create [args...]         Create a new storage environment container"
	echo "        -s=n, --size=n       Specifies the size of the container, in bytes"
	echo "        -f=f, --filename=f   Specifies the filename of the container"
	echo
}

if [[ $# -eq 0 ]]; then
	# no parameters
	debug "no parameters given, print out usage"
	usage
	exit 0
fi

while thinder_getopt "${1:-}" opt val; do
	debug "processing subcommand option $opt"
	case $opt in
		--help | -h)
			usage
			exit 0;
			;;
		*)
			error "unknown option: $opt"
			exit 1
	esac
	shift
done

case "${1:-environment}" in
	create)
		shift
		size=""
		filename=$THINDER_BTRFS_IMAGE
		while thinder_getopt "${1:-}" opt val; do
			debug "processing subsubcommand option $opt"
			case $opt in
				--size | -s)
					if [[ "$val" == "" ]]; then
						critical "$opt expects a parameter"
						exit 1
					fi
					size=$val
					;;
				*)
					critical "unknown option: $opt"
					exit 1
			esac
			shift
		done
		if [[ "$size" == "" ]]; then
			critical "please specify the size of the container (--size=n)"
			exit 1
		fi
		echo -n "Continue creating container at $filename [y/N] "
		read confirm
		if [[ "$confirm" == "y" ]]; then
			echo -n "    creating container at $filename... "
			if ! fallocate -l "$size" "$filename"; then
				critical "error allocating storage container"
				exit 1
			fi
			echo "done"
		else
			warning "Abort."
		fi
		;;
	image)
		critical todo
		;;
	instance)
		critical todo
		;;
	*)
		critical "'${1}' is not a valid $file subcommand"
		exit 1
esac