#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail; shopt -s nullglob
root=${0%/*}
file=$(basename "${BASH_SOURCE[0]}")

. $root/lib/cli-utils
. $root/lib/thinder-environment.sh

THINDER_ROOT=/var/thinder
THINDER_NET_BRIDGE=thinder0
THINDER_NET_ADDR="10.0.0.1/24"
THINDER_BTRFS_IMAGE=/thinder_storage
LOG_LEVEL=${LOG_LEVEL:-5}

function usage {
	local cmdlen=${#file}
	echo "Usage: ${file} [OPTIONS] COMMAND [args...]"
	echo
	echo "Linux app containers on steroids"
	echo
	echo "Options:"
	echo "  --help                   Print this usage information"
	echo "  --storage-root=d         Specify storage environment root"
	echo "  --storage-container=f    Specify default storage container"
	echo
	echo "Commands:"
	pushd $root > /dev/null
	for subcmd in *; do
		if [[ -d "$root/$subcmd" ]] && [[ -f "$root/${subcmd}/${subcmd}" ]] && [[ $subcmd == "${file}-"* ]]; then
			local name=${subcmd:cmdlen+1}
			echo -n "    ${name}"
			local n=$((16-${#name}))
			printf ' %.0s' $(seq 1 $n)
			"${root}/${subcmd}/${subcmd}" __descr
		fi
	done
	popd > /dev/null
	echo
}

if [[ $# -eq 0 ]]; then
	# no parameters
	debug "no parameters given, print out usage"
	usage
	exit 0
fi

while thinder_getopt "${1:-}" opt val; do
	debug "processing global option $opt"
	case $opt in
		--help | -h)
			usage
			exit 0;
			;;
		--verbose | -v | --loglevel)
			if [[ "${val:-}" == "" ]]; then val=5; fi
			if [ "$val" -ge 1 -a "$val" -le 7 ]; then
				LOG_LEVEL=$val
			else
				error "log level should be between 1..7 inclusive"
				exit 1
			fi
			;;
		--storage-root)
			[[ "$val" == "" ]] && critical "$opt expects a parameter" && exit 1
			THINDER_ROOT="$val"
			;;
		--storage-container)
			[[ "$val" == "" ]] && critical "$opt expects a parameter" && exit 1
			THINDER_BTRFS_IMAGE="$val"
			;;
		*)
			error "unknown option: $opt"
			exit 1
	esac
	shift
done

if [[ ! "${1:-}" == "" ]]; then
	subcmd=$1
	if [[ -d "${file}-${subcmd}" ]] && [[ -f "${file}-${subcmd}/${file}-${subcmd}" ]]; then
		shift
		export LOG_LEVEL THINDER_ROOT THINDER_NET_BRIDGE THINDER_NET_ADDR THINDER_BTRFS_IMAGE
		"$root/${file}-${subcmd}/${file}-${subcmd}" $@
	else
		critical "'${subcmd}' is not a valid Thinder subcommand"
		exit 1
	fi
fi

exit 0