#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail; shopt -s nullglob
root=${0%/*}
file=$(basename "${BASH_SOURCE[0]}")
cd $root

. ../lib/cli-utils

set_thinder_description "List all available images"

echo "hoi"