#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail; shopt -s nullglob
root=${0%/*}
file=$(basename "${BASH_SOURCE[0]}")
cd $root

. ../lib/cli-utils

set_thinder_command "Mount a local filesystem to an internal instance filesystem"

echo "hoi"